### ISSUE TITLE
Installation error using gcc

### ISSUE THREAD

**Issue by hugo01bg** [mattkjames7/JupiterMag#2]
<img width="893" alt="Screenshot 2024-01-31 at 16 17 32" src="https://github.com/mattkjames7/JupiterMag/assets/158312261/d133b7a2-0657-46fe-87f7-1dbbe0bb8016">

Undergrads working on project. Trying to download repository, but having trouble with a gcc error. Is clang the problem?

**Comment by mattkjames7** [comment]
Hi hugo01bg,

Thanks for using my code and finding this bug!

Unfortunately it appears that I had missed an `#include <sstream>` or two - I have made fixes to the relevant code in both `JupiterMag` (now version 1.3.1) and `libjupitermag` (now version 1.4.1).

Hopefully my changes will fix this error for you - please do let me know if it works!

Cheers,
Matt.

**Comment by hugo01bg** [comment]
Hi Matt,

Thank you very much! I will try again and let you know.

Best,
Hugo
________________________________

**Comment by hugo01bg** [comment]
Works now! Thanks
